# **Khushdev Pandit**
# **Roll no: 2020211** 
# *Assignment Question-1*

#

# **Q1 Part-1**

In [9]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
import glob

images = glob.glob('Chess_Images/*.jpg')
print("Number of images: ", len(images))

Number of images:  28


In [10]:
def find_world_and_image_points(images, checkerboard_size=(5,5)):
    # Arrays to store object points and image points from all the images.
    objects_points = []     # 3d points in real world space
    image_points = []       # 2d points in image plane.

    # Prepare world coordinate for 3D-object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0), and so on
    objp = np.zeros((1, checkerboard_size[0]*checkerboard_size[1], 3), np.float32)
    objp[0,:,:2] = np.mgrid[0:checkerboard_size[0], 0:checkerboard_size[1]].T.reshape(-1, 2)
    
    # termination criteria
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
    
    # Step through the list and search for chessboard corners
    cnt = 0
    for fname in images:
        cnt += 1
        print("Processing Image-" + str(cnt), ": ", fname)
        
        # Read the image, invert it and convert to grayscale
        img = cv2.imread(fname)
        inverted_img = np.array(255 - img, dtype=np.uint8)
        gray_img = cv2.cvtColor(inverted_img, cv2.COLOR_BGR2GRAY)

        # Locate the chessboard corners in the chessboard image
        ret, corners = cv2.findChessboardCorners(image=gray_img, patternSize=checkerboard_size, 
                flags=cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)

        # If corner is found, add object points, image points
        if ret == True:
            print("Corners found")
            # Refined chessboard corners for better accuracy
            corners_refined = cv2.cornerSubPix(gray_img, corners, (11,11), (-1,-1), criteria)

            # print('Sum of Difference in corner and refined corner:', (corners_refined-corners).sum())
            objects_points.append(objp)
            image_points.append(corners_refined)

            # Draw the corners
            corners_img = cv2.drawChessboardCorners(img, checkerboard_size, corners_refined, ret)
            for corner in corners_refined.squeeze():
                coord = (int(corner[0]), int(corner[1]))
                cv2.circle(img=corners_img, center=coord, radius=33, color=(255, 0, 0), thickness=15)

            plt.imsave("Chess_Corners/" + str(fname.split('\\')[-1].split('.')[0] + '.png'), corners_img)

    return objects_points, image_points

In [11]:
# Locate the chessboard corners in the chessboard image
checkerboard_size=(5,5)
objects_points, image_points = find_world_and_image_points(images, checkerboard_size)

Processing Image-1 :  Chess_Images\IMG_20230402_131411.jpg
Corners found
Processing Image-2 :  Chess_Images\IMG_20230402_131417.jpg
Corners found
Processing Image-3 :  Chess_Images\IMG_20230402_131422.jpg
Corners found
Processing Image-4 :  Chess_Images\IMG_20230402_131426.jpg
Corners found
Processing Image-5 :  Chess_Images\IMG_20230402_131436.jpg
Corners found
Processing Image-6 :  Chess_Images\IMG_20230402_131443.jpg
Corners found
Processing Image-7 :  Chess_Images\IMG_20230402_131452.jpg
Corners found
Processing Image-8 :  Chess_Images\IMG_20230402_131457.jpg
Corners found
Processing Image-9 :  Chess_Images\IMG_20230402_131500.jpg
Corners found
Processing Image-10 :  Chess_Images\IMG_20230402_131506.jpg
Corners found
Processing Image-11 :  Chess_Images\IMG_20230402_131512.jpg
Corners found
Processing Image-12 :  Chess_Images\IMG_20230402_131536.jpg
Corners found
Processing Image-13 :  Chess_Images\IMG_20230402_131614.jpg
Corners found
Processing Image-14 :  Chess_Images\IMG_2023040

In [12]:
img = cv2.imread(images[0])
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objects_points, image_points, img.shape[:2],None,None)

print("ret : \n", ret)
print("Camera matrix : \n", mtx)
print("dist : \n", dist)
print("rvecs : \n", rvecs) 
print("tvecs : \n", tvecs)

ret : 
 2.9029874512404708
Camera matrix : 
 [[3.59083306e+03 0.00000000e+00 2.18587381e+03]
 [0.00000000e+00 3.61682218e+03 1.15224849e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
dist : 
 [[ 0.35342384 -3.46665081 -0.02122771 -0.01373224  5.72094171]]
rvecs : 
 (array([[-0.00406735],
       [-0.03144819],
       [ 0.01280105]]), array([[0.33383884],
       [0.44011248],
       [1.56743828]]), array([[0.19339237],
       [0.34538016],
       [0.29027815]]), array([[-0.05547995],
       [ 0.19086731],
       [ 0.18717577]]), array([[-0.2310805 ],
       [-0.67319414],
       [ 0.0059064 ]]), array([[-0.34538965],
       [-0.17481163],
       [ 0.04018264]]), array([[0.45470841],
       [0.02882068],
       [0.01258321]]), array([[-0.07546691],
       [-0.02099982],
       [ 0.03018688]]), array([[0.13696698],
       [0.09113442],
       [1.43380997]]), array([[0.81501916],
       [0.31752465],
       [0.8998387 ]]), array([[ 0.39127818],
       [ 0.80719848],
       [-0.047602